# Generated by Django 2.2.5 on 2019-09-09 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, max_length=1000, verbose_name='Дивизион')),
                ('link', models.CharField(db_index=True, max_length=1000, verbose_name='Ссылка на дивизион')),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('chemp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fill.Chemps', verbose_name='Чемпионат')),
            ],
            options={
                'verbose_name': 'Дивизион',
                'verbose_name_plural': 'Дивизионы',
                'ordering': ['sort'],
            },
        ),
    ]
