# Generated by Django 2.2.5 on 2019-09-11 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0003_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('div', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fill.Divs', verbose_name='Дивизион')),
            ],
            options={
                'verbose_name': 'Список туров',
                'verbose_name_plural': 'Туры',
                'ordering': ['number'],
            },
        ),
    ]
