# Generated by Django 2.2.5 on 2019-09-11 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0006_gamestext'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesTextReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('report', models.TextField(verbose_name='Текстовый отчет')),
                ('gametext', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fill.GamesText', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Текст матчей',
                'verbose_name_plural': 'Тексты Матчей',
                'ordering': ['id'],
            },
        ),
    ]
