# Generated by Django 2.2.5 on 2019-09-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0008_gamestextreport_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestextreport_main',
            name='arbitr',
            field=models.CharField(default='', max_length=200, verbose_name='Арбитр'),
        ),
        migrations.AddField(
            model_name='gamestextreport_main',
            name='wheater',
            field=models.CharField(default='', max_length=10, verbose_name='Погода'),
        ),
    ]
