# Generated by Django 2.2.5 on 2019-09-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0009_auto_20190913_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamestextreport_main',
            options={'ordering': ['id'], 'verbose_name': 'Основная статистика матчей', 'verbose_name_plural': 'Основная статистика матчей'},
        ),
    ]
