# Generated by Django 2.2.5 on 2019-09-13 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0010_auto_20190913_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestextreport_main',
            name='gametext',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fill.GamesTextReport', verbose_name='Игра'),
        ),
    ]
