# Generated by Django 2.2.5 on 2019-09-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0012_auto_20190914_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('number', models.IntegerField(verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезон',
                'ordering': ['number'],
            },
        ),
    ]
