# Generated by Django 2.2.5 on 2019-09-23 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0013_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='turs',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fill.Season', verbose_name='Сезон'),
        ),
    ]
