# Generated by Django 2.2.5 on 2019-09-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0014_turs_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesTextReport_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Имя')),
                ('rating', models.FloatField(verbose_name='Оценка')),
                ('minutes', models.IntegerField(verbose_name='Минута')),
                ('card', models.CharField(default='', max_length=50, verbose_name='Карточка')),
                ('capitan', models.IntegerField(verbose_name='Капитан')),
                ('im', models.IntegerField(verbose_name='ИМ')),
                ('count_find', models.IntegerField(verbose_name='Количество в матче')),
                ('stat_kick', models.IntegerField(verbose_name='Удары ногой')),
                ('stat_kick_ok', models.IntegerField(verbose_name='Удары ногой OK')),
                ('stat_shtanga', models.IntegerField(verbose_name='Штанги')),
                ('stat_offside', models.IntegerField(verbose_name='Офсайд')),
                ('stat_kick_far', models.IntegerField(verbose_name='Дальние удары')),
                ('stat_kick_far_ok', models.IntegerField(verbose_name='Дальние удары OK')),
                ('stat_head', models.IntegerField(verbose_name='Удары головой')),
                ('stat_head_ok', models.IntegerField(verbose_name='Удары головой OK')),
                ('stat_block', models.IntegerField(verbose_name='Блокированные')),
                ('stat_pass', models.IntegerField(verbose_name='Пасы')),
                ('stat_pass_ok', models.IntegerField(verbose_name='Пасы OK')),
                ('stat_cross', models.IntegerField(verbose_name='Навесы')),
                ('stat_cross_ok', models.IntegerField(verbose_name='Навесы OK')),
                ('stat_dribbling', models.IntegerField(verbose_name='Дриблинг')),
                ('stat_dribbling_ok', models.IntegerField(verbose_name='Дриблинг OK')),
                ('stat_tackle', models.IntegerField(verbose_name='Отбор')),
                ('stat_tackle_ok', models.IntegerField(verbose_name='Отбор OK')),
                ('stat_up', models.IntegerField(verbose_name='Верховые единоборства')),
                ('stat_up_ok', models.IntegerField(verbose_name='Верховые единоборства OK')),
                ('stat_perehvat', models.IntegerField(verbose_name='Перехваты')),
                ('stat_poter', models.IntegerField(verbose_name='Потери')),
                ('stat_foul', models.IntegerField(verbose_name='Фолы')),
                ('stat_foul_him', models.IntegerField(verbose_name='Фолы на нём')),
                ('stat_save', models.IntegerField(verbose_name='Сейвы')),
                ('stat_save_ok', models.IntegerField(verbose_name='Сейвы OK')),
                ('gametext', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fill.GamesText', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Статистика игроков из матчей',
                'verbose_name_plural': 'Статистика игроков из матчей',
                'ordering': ['id'],
            },
        ),
    ]
