# Generated by Django 2.2.5 on 2019-09-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0015_gamestextreport_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestextreport_player',
            name='player_id',
            field=models.IntegerField(default=0, verbose_name='ID игрока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamestextreport_player',
            name='team',
            field=models.CharField(default='', max_length=200, verbose_name='Команда'),
        ),
    ]
