# Generated by Django 2.2.5 on 2019-09-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0016_auto_20190929_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestextreport_player',
            name='basis',
            field=models.IntegerField(default=0, verbose_name='Основа'),
            preserve_default=False,
        ),
    ]
