# Generated by Django 2.2.5 on 2019-09-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0017_gamestextreport_player_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestextreport_player',
            name='trauma',
            field=models.IntegerField(default=0, verbose_name='Травма'),
            preserve_default=False,
        ),
    ]
