# Generated by Django 2.2.5 on 2019-09-29 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0019_gamestextreport_player_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesTextReport_Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('minutes', models.IntegerField(verbose_name='Минута')),
                ('player_goal', models.CharField(default='', max_length=200, verbose_name='Забивший гол')),
                ('player_pass', models.CharField(default='', max_length=200, verbose_name='Отдавший пас')),
                ('team', models.CharField(default='', max_length=200, verbose_name='Команда')),
                ('home', models.IntegerField(verbose_name='Дома')),
                ('own_goal', models.IntegerField(verbose_name='Автогол')),
                ('penalty', models.IntegerField(verbose_name='Пенальти')),
                ('type', models.CharField(default='', max_length=200, verbose_name='Тип гола')),
                ('gametext', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fill.GamesText', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Статистика голов из матчей',
                'verbose_name_plural': 'Статистика голов из матчей',
                'ordering': ['id'],
            },
        ),
    ]
