# Generated by Django 2.2.5 on 2019-10-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0021_stat_players_list_goal_stat_players_list_goalandpass_stat_players_list_pass_stat_team_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat_players_list_goal',
            name='team',
            field=models.CharField(default='', max_length=200, verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='stat_players_list_goalandpass',
            name='team',
            field=models.CharField(default='', max_length=200, verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='stat_players_list_pass',
            name='team',
            field=models.CharField(default='', max_length=200, verbose_name='Команда'),
        ),
    ]
