# Generated by Django 2.2.5 on 2019-10-06 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0024_stat_players_pivot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat_Players_GoalAndPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Игрок')),
                ('team', models.CharField(default='', max_length=200, verbose_name='Команда')),
                ('goal', models.IntegerField(verbose_name='Пасов')),
                ('pases', models.IntegerField(verbose_name='Пасов')),
                ('played', models.IntegerField(verbose_name='Матчей')),
                ('div', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fill.Divs', verbose_name='Дивизион')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fill.Season', verbose_name='Сезон')),
            ],
        ),
    ]
