# Generated by Django 2.2.5 on 2019-10-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0025_stat_players_goalandpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesTextReport_Player_NameTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Имя')),
                ('team', models.CharField(default='', max_length=200, verbose_name='Команда')),
            ],
        ),
    ]
