# Generated by Django 2.2.5 on 2019-10-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0026_gamestextreport_player_nameteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestextreport_player_nameteam',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='gamestextreport_player_nameteam',
            name='team',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Команда'),
        ),
    ]
