# Generated by Django 2.2.5 on 2019-10-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0029_gamestextreport_goal_playergoalteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesTextReport_Goal_PlayerPassTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, default='', max_length=200, verbose_name='Имя')),
                ('team', models.CharField(db_index=True, default='', max_length=200, verbose_name='Команда')),
            ],
        ),
    ]
