# Generated by Django 2.2.5 on 2019-10-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0030_gamestextreport_goal_playerpassteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat_players_goalandpass',
            name='goal_and_pases',
            field=models.IntegerField(default=0, verbose_name='Гол+Пас'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stat_players_goalandpass',
            name='goal',
            field=models.IntegerField(verbose_name='Голов'),
        ),
    ]
