# Generated by Django 2.2.5 on 2019-10-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0035_auto_20191009_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat_players_playedmaxtime',
            name='player_id',
            field=models.IntegerField(default=0, verbose_name='ID игрока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat_players_playedmaxtime',
            name='stat_cross_no',
            field=models.IntegerField(default=0, verbose_name='Навесы NO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat_players_playedmaxtime',
            name='stat_dribbling_no',
            field=models.IntegerField(default=0, verbose_name='Дриблинг NO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat_players_playedmaxtime',
            name='stat_head_no',
            field=models.IntegerField(default=0, verbose_name='Удары головой NO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat_players_playedmaxtime',
            name='stat_kick_far_no',
            field=models.IntegerField(default=0, verbose_name='Дальние удары NO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat_players_playedmaxtime',
            name='stat_kick_no',
            field=models.IntegerField(default=0, verbose_name='Удары ногой NO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat_players_playedmaxtime',
            name='stat_pass_no',
            field=models.IntegerField(default=0, verbose_name='Пасы NO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat_players_playedmaxtime',
            name='stat_save_no',
            field=models.IntegerField(default=0, verbose_name='Сейвы NO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat_players_playedmaxtime',
            name='stat_tackle_no',
            field=models.IntegerField(default=0, verbose_name='Отбор NO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat_players_playedmaxtime',
            name='stat_up_no',
            field=models.IntegerField(default=0, verbose_name='Верховые единоборства NO'),
            preserve_default=False,
        ),
    ]
