# Generated by Django 2.2.5 on 2019-10-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0036_auto_20191009_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat_players_playedmaxtime_list',
            name='player_id',
            field=models.IntegerField(default=0, verbose_name='ID игрока'),
            preserve_default=False,
        ),
    ]
