# Generated by Django 2.2.5 on 2019-10-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0037_stat_players_playedmaxtime_list_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat_players_playedmaxtime',
            name='number_in_team',
            field=models.FloatField(default=0, verbose_name='Примерный номер'),
            preserve_default=False,
        ),
    ]
