# Generated by Django 2.2.5 on 2019-10-09 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0038_stat_players_playedmaxtime_number_in_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat_Players_PlayedMaxTime_Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, default='', max_length=200, verbose_name='Имя')),
                ('team', models.CharField(db_index=True, default='', max_length=200, verbose_name='Команда')),
                ('player_id', models.IntegerField(verbose_name='ID игрока')),
                ('pases', models.IntegerField(verbose_name='Пасов')),
                ('div', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fill.Divs', verbose_name='Дивизион')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fill.Season', verbose_name='Сезон')),
            ],
        ),
        migrations.CreateModel(
            name='Stat_Players_PlayedMaxTime_Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, default='', max_length=200, verbose_name='Имя')),
                ('team', models.CharField(db_index=True, default='', max_length=200, verbose_name='Команда')),
                ('player_id', models.IntegerField(verbose_name='ID игрока')),
                ('goal', models.IntegerField(verbose_name='Голов')),
                ('div', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fill.Divs', verbose_name='Дивизион')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fill.Season', verbose_name='Сезон')),
            ],
        ),
    ]
