# Generated by Django 2.2.5 on 2019-10-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0039_stat_players_playedmaxtime_goals_stat_players_playedmaxtime_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat_players_playedmaxtime',
            name='goal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голов'),
        ),
        migrations.AlterField(
            model_name='stat_players_playedmaxtime',
            name='pases',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голевых пасов'),
        ),
    ]
