# Generated by Django 2.2.5 on 2019-10-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill', '0041_gamestextreport_playerstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestextreport_playerstat',
            name='goal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голов'),
        ),
        migrations.AddField(
            model_name='gamestextreport_playerstat',
            name='pases',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голевых пасов'),
        ),
    ]
